### ISSUE TITLE
hid_printer.v bug: incorrect blocking assignment

### ISSUE THREAD

**Issue by mbalestrini** [nand2mario/usb_hid_host#4]
I just realized I was always getting "0000" on the "x0dMouse y" coordinate and I found this:

https://github.com/nand2mario/usb_hid_host/blob/9697007fc60994e6a73b8a7834154b0dd851b814/boards/common/hid_printer.v#L76

I thought it would be easier for you to correct it, but I can create a PR if you prefer

**Comment by nand2mario** [comment]
Thanks for catching this!
